version: '3.8'

services:
  kubepilot:
    build: .
    container_name: kubepilot_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - KUBECONFIG_PATH=/app/config/kubeconfig.yaml
    volumes:


      - /chemin/absolu/vers/ton/vrai/kubeconfig.yaml:/app/config/kubeconfig.yaml:ro

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M